### ISSUE TITLE
Hermes_python loop forever au lancement de action-spotify.py

### ISSUE THREAD

**Issue by sifus** [Ultchad/snips-skill-spotifywebapi#18]
Hello,

je suis confronter a un loop forever quand je lance le action-spotify.py

```
(venv) pi@snips-master:/var/lib/snips/skills/snips-skill-spotifywebapi $ sudo python action-spotifywebapi.py
Get the cached token: OK
^CTraceback (most recent call last):
  File "action-spotifywebapi.py", line 600, in <module>
    .subscribe_intent('Tealque:modeDisable', modeDisable)\
  File "/usr/local/lib/python2.7/dist-packages/hermes_python/hermes.py", line 282, in loop_forever
    sleep(.1)
KeyboardInterrupt
```

**Comment by Ultchad** [comment]
C'est a dire ?
Tu a eu le message `Get the cached token: OK` et le programme ne rend pas le prompt, il entre dans la boucle, et c'est toi qui a fait `CTRL+C` pour killer le process ?

Si ce n'est pas sa je n'ai pas compris, pourrais tu me donner plus d'info, (méthode d'installation du skill, de snips)
Si c'est sa c'est normal, comme pour l'issue #12 c'est comme sa que sont fait les skill sur Snips, c'est le service `snips-skill-server` qui lance les skill et gère leur cycle de vie

**Comment by sifus** [comment]
en fait je quitte manuellement car ca tourne en boucle et ca ne me rend pas le contrôle de la console... si je ne fais pas quitter je ne peux plus rien écrire...

j'essaye de résoudre un probleme, le skill spotify ne lance pas l'action demandée sur mon snips. Il comprend l'action (quand je regarde sam watch) mais me retourne :

`17:52:23] [Dialogue] session with id '7922a739-61b2-4d3b-a7c9-12a9243c19b1' was ended on site default. The session was ended because one of the component didn't respond in a timely manner`

**Comment by Ultchad** [comment]
Alors comme je l'ai dit c'est normal qu'il ne rende pas la main, comme dans l'issue #12 c'est snips-skill-server qui gère ça 

Peux tu donner la copie de la session complète de 
```bash
sam watch
```
ou 
```bash
snips-watch
```
Car on voie que le composants n'a pas répondu dans les temps, mais de quel composants s'agit il. 

Et si tu utilises sam peux tu me donner le 
```bash
sam statut
```
avant de faire tes test pour voir si tout les services son ok

**Comment by sifus** [comment]
Ah bah tiens pour la premiere fois Snips me respond quelque chose :
**"désoler aucun équipement actif n'a été trouvé"**


voila ce que j'obtient au lancement du .py dans le venv :

```
(venv) pi@raspberrypi:/var/lib/snips/skills/snips-skill-spotifywebapi $ sudo python action-spotifywebapi.py
Get the cached token: OK
Search artist: Matthieu Chedid
Search found a item for <type 'type'>: Matthieu Chedid 	>	Louis, Matthieu, Joseph & Anna Chedid - spotify:artist:4t00sis6zJ8V9x2MFvfcj2
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/hermes_python/ffi/wrappers.py", line 61, in convert_arguments_when_invoking_function
    return func(hermes_client, *parsed_args)
  File "action-spotifywebapi.py", line 320, in playArtist
    _sp_client.start_playback(context_uri=uri, uris=None)
AttributeError: 'Spotify' object has no attribute 'start_playback'
```


sam watch :

```
[01:31:40] Watching on localhost:1883 (MQTT)
[01:31:42] [Hotword] detected on site default, for model default
[01:31:42] [Asr] was asked to stop listening on site default
[01:31:42] [Hotword] was asked to toggle itself 'off' on site default
[01:31:42] [Dialogue] session with id '8922bb42-aecb-44ff-97e0-e37288285941' was started on site default
[01:31:42] [AudioServer] was asked to play a wav of 41.1 kB with id '1280c6fc-527b-4ef7-89db-6dc4abfeaed6' on site default
[01:31:43] [AudioServer] finished playing wav with id '1280c6fc-527b-4ef7-89db-6dc4abfeaed6'
[01:31:43] [Asr] was asked to listen on site default
[01:31:46] [Asr] captured text "joue du matthieu chedid" in 2.0s
[01:31:46] [Asr] was asked to stop listening on site default
[01:31:46] [AudioServer] was asked to play a wav of 93.1 kB with id '205da5f0-3961-46d0-a56c-265650759b03' on site default
[01:31:47] [AudioServer] finished playing wav with id '205da5f0-3961-46d0-a56c-265650759b03'
[01:31:47] [Nlu] was asked to parse input "joue du matthieu chedid"
[01:31:47] [Nlu] detected intent Tealque:playArtist with confidence score 1.000 for input "joue du matthieu chedid"
              Slots ->
                 artist -> Matthieu Chedid (confidence: 1.000)
[01:31:47] [Dialogue] New intent detected Tealque:playArtist with confidence 1.000
              Slots ->
                 artist -> Matthieu Chedid (confidence: 1.000)
[01:31:53] [Dialogue] session with id '8922bb42-aecb-44ff-97e0-e37288285941' was ended on site default. The session was ended because one of the component didn't respond in a timely manner
[01:31:53] [Asr] was asked to stop listening on site default
[01:31:53] [Hotword] was asked to toggle itself 'on' on site default
```


sam status :

```
OS version ................... Raspbian GNU/Linux 9 (stretch)
Installed assistant .......... jeedom
Language ..................... fr
Hotword ...................... jarvis
ASR engine ................... snips
Status ....................... Live

Service status:

snips-analytics .............. 0.62.3 (not running)
snips-asr .................... 0.62.3 (running)
snips-audio-server ........... 0.62.3 (running)
snips-dialogue ............... 0.62.3 (running)
snips-hotword ................ 0.62.3 (running)
snips-nlu .................... 0.62.3 (running)
snips-skill-server ........... 0.62.3 (running)
snips-tts .................... 0.62.3 (running)
```

**Comment by sifus** [comment]
au fait ce n'est pas expliqué dans votre documentation ou sur la description de l'app dans Snips qu'il faut installer Hermes et Spotify ?...

**Comment by sifus** [comment]
Bon bah probleme resolu en installant manuellement paho-mqtt-1.4.0, Hermes python, et spotipy.

je trouve Sam très mauvais pour parser les app du Snips Console. J'ai du aller dans chaque app traficoter pour que chacune marche.

**Comment by sifus** [comment]
Ca ne marche deja plus. Toujours cette ligne !
`
[03:11:05] [Dialogue] session with id '89cf5ba4-c592-46a4-ae66-d0fb5a58afb6' was ended on site default. The session was ended because one of the component didn't respond in a timely manner`

**Comment by Ultchad** [comment]
Il n'y a pas besoin d'installer spotify, cette app vas utilisé l'API Web (des commande accessible sur le site de spotify) qui controle le compte connecté
Pour hermes, c'est une librairie python qui est installé dans le virtualenv au moment de l'installation de l'app via la commande `./setup.sh` contenu dans l'app, si tu a utilisé sam install action, il l'a fait automatiquement normalement

Je regarde sa, dès que j'ai un moment, a première vue il n'a pas récuprèré la bonne version de spotipy (librairie qui utilise l'API web spotify), car dans les première version `start_playback` la fonction que ton app ne trouve pas , n’était pas présente

**Comment by sifus** [comment]
Pourtant pour Spotipy j'ai bien ca quand je veux generer un token :

```
pi@raspberrypi:/var/lib/snips/skills/snips-skill-spotifywebapi $ sudo ./token-generator.py
Traceback (most recent call last):
  File "./token-generator.py", line 4, in <module>
    import spotipy
ImportError: No module named spotipy
```

**Comment by Ultchad** [comment]
mais a tu fait 
`. venv/bin/activate`
pour activé le virtualenv avant de faire de lancé le script ?

**Comment by sifus** [comment]
oui ca ne change rien :

```
pi@raspberrypi:/var/lib/snips/skills/snips-skill-spotifywebapi $ . venv/bin/activate
(venv) pi@raspberrypi:/var/lib/snips/skills/snips-skill-spotifywebapi $ sudo ./token-generator.py
Traceback (most recent call last):
  File "./token-generator.py", line 4, in <module>
    import spotipy
ImportError: No module named spotipy
```

**Comment by Ultchad** [comment]
Pourquoi utilise tu sudo pour éxécuté `token-generator.py` ?
Il faut évité d'utilisé les droits root pour exécuté ce genre de script

quand tu utilise sudo tu passe sur un autre utilisateur (pour faire simple)
si tu a vraiment besoin de sudo utilise 
```bash
sudo venv/bin/python token-generator.py
```
ce sera le python contenue dans le virtual env qui sera exécute et non celui du system

**Comment by Ultchad** [comment]
Cela a t'il résolut le problème ?

**Comment by Ultchad** [comment]
Tu n'auras qu'à recouvrir le ticket si besoin
